"""empty message

Revision ID: 494d5e77a75a
Revises: aa2b9880474e
Create Date: 2018-06-27 04:25:07.454359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494d5e77a75a'
down_revision = 'aa2b9880474e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
