"""empty message

Revision ID: aa2b9880474e
Revises: users
Create Date: 2018-06-27 03:34:39.807273

"""
from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2b9880474e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
