FROM node:8.11

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app
RUN npm install
#RUN npm install react-scripts@1.1.0 -g --silent

CMD ["npm", "start"]
